config/routes.rb
Rails.application.routes.draw do

 

  devise_for :users , controllers:
                     { omniauth_callbacks: "users/omniauth_callbacks" }
                     { registrations: "users/registrations" }
  devise_scope :users do
  end
  namespace :admin, path: 'asigaiboho' do
    resources :reserves 
    resources :users
    get 'search', to: 'reserves#search'
    get 'searchs', to: 'users#searchs'
  end

    resources :reserves 
    root 'welcome#index'
    resources :users
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  scope :published_since, -> (date) { where(published: true).where('published_date <= ?', date) }
  acts_as_paranoid
  
  resourcify
  # rolify套件
  validates :name, :email, :address, :cellphone, :appointment, presence: true
  
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  # 原本是input.to_s.parameterize，但是parameterize只支援英文跟數字，所以改用babosa的to_slug
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize.to_s
  end
  
  # 定義slug_candidates，預設會找第一個，如果有重複的name就會找第二個（name-price），最後才會生成亂序
  def slug_candidates
    [
      :name,
      [:name]
    ]
  end
end

app/controllers/admin/reserves_controller.rb
class Admin::ReservesController < ApplicationController
    before_action  :find_user_reserve, only: [:edit, :update, :destroy, :show]
    authorize_resource :admin
    def index
      @pagy, @reserves = pagy(Reserve.order(id: :desc), items: 10)
    end
  
    def edit
    end
  
    def show
    end
  
    def update
      if @reserve.update(reserve_params)
        redirect_to admin_reserves_path , notice:'更改成功'
      else
        render :edit
      end
    end
  
    def destroy
      @reserve.update(deleted_at: Time.now)
      redirect_to admin_reserves_path
    end

    def search
      if params[:keyword]
        @pagy, @reserves = pagy(Reserve.where("name LIKE ? OR email LIKE ? OR status LIKE ?", "%#{params[:keyword]}%","%#{params[:keyword]}%", "%#{params[:keyword]}%").order(id: :desc), items: 10)
      else
        @pagy, @reserves = pagy(Reserve.order(id: :desc), items: 10)
      end
      render :index
    end
    
    private
      def reserve_params
        params.require(:reserve).permit(:name, 
                                        :email, 
                                        :telephone, 
                                        :address, 
                                        :cellphone, 
                                        :appointment, 
                                        :genre, 
                                        :brand,
                                        :status,
                                        :remark,
                                        :image,
                                        :determine_time)
      end
  
      def find_user_reserve
        @reserve = Reserve.friendly.find(params[:id])
      end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  before_action  :authenticate_user!
  before_action  :find_user_reserve, only: [:edit, :update, :destroy, :show]
  authorize_resource
  def index
    @reserves = current_user.reserves.order(id: :desc)
   
  end
  def new
    @reserve = current_user.reserves.new
  end

  def create
    @reserve = current_user.reserves.new(reserve_params)
    if @reserve.save
      MailWorker.perform_at(5.seconds.from_now,
                            @reserve.name,
                            @reserve.cellphone,
                            @reserve.address,
                            @reserve.appointment,
                            @reserve.brand,
                            @reserve.genre,
                            @reserve.telephone,
                            @reserve.email,
                            @reserve.remark)
      redirect_to root_path, notice:'填寫成功,請等候老闆與您聯繫~'
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
		if @reserve.update(reserve_params)
			redirect_to root_path, notice:'更改成功'
		else
			## 待處理
			render :edit
		end
	end

  def destroy
		@reserve.update(deleted_at: Time.now)
		redirect_to '/reserves'
	end

  private
    def reserve_params
      params.require(:reserve).permit(:name, 
                                      :email, 
                                      :telephone, 
                                      :address, 
                                      :cellphone, 
                                      :appointment, 
                                      :genre, 
                                      :brand,
                                      :remark,
                                      :image,
                                      :determine_time)
    end

    def find_user_reserve
      @reserve = current_user.reserves.friendly.find(params[:id])
    end
end

app/views/admin/reserves/_form.html.erb
<div class="relative bg-white">
  <div class="absolute inset-0">
    <div class="absolute inset-y-0 left-0 w-1/2 "></div>
  </div>
  <div class="relative max-w-7xl mx-auto lg:grid lg:grid-cols-5">
    <div class="bg-white py-16 px-4 sm:px-6 lg:col-span-2 lg:px-8 lg:py-24 xl:pr-12">
      <div class="max-w-lg mx-auto">
        <h2 class="text-2xl font-extrabold tracking-tight text-blue-400 sm:text-3xl">
          衣級棒新北三重服務團隊
        </h2>
        <p class="mt-3 text-lg leading-6 text-black">
          衣級棒專業洗衣機清洗-清洗內槽-秉持著一顆服務熱忱的心。讓您不再為洗衣服而感到困擾， 給您一個舒適潔淨的洗衣空間。將每個家庭洗衣機的髒汙轉化成煥然一新的面貌。
        </p>
        <dl class="mt-8 text-base text-black">
          <div>
            <dt class="sr-only">Postal address</dt>
            <dd>
               <p>
                直立式價格: 1300<br>
                滾筒式價格: 3500<br>
                LG上下洗價格: 6000<br>
                如路程較遠直立式需酌收車馬費
              </p>
            </dd>
          </div>
          <div class="mt-6">
            <dt class="sr-only">Phone number</dt>
            <dd class="flex">
              <!-- Heroicon name: outline/phone -->
              <svg class="flex-shrink-0 h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
              </svg>
              <span class="ml-3">
                0933750166 劉師傅
              </span>
            </dd>
          </div>
          <div class="mt-3">
            <dt class="sr-only">Email</dt>
            <dd class="flex">
              <!-- Heroicon name: outline/mail -->
              <svg class="flex-shrink-0 h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              <span class="ml-3">
                washyou178@gmail.com
              </span>
            </dd>
          </div>
        </dl>
          <a href="https://www.facebook.com/LINE0933750166" class= 'block text-blue-400 text-2xl mt-10 '>衣級棒-新北三重粉絲專頁</a>

      </div>
    </div>
    <div class="bg-white py-16 px-4 sm:px-6 lg:col-span-3 lg:py-24 lg:px-8 xl:pl-12">
      <div class="max-w-lg mx-auto lg:max-w-none">
        <%= form_with(model: reserve, url: admin_reserve_path) do |f| %>
          <div>
            <%= f.label :name, '姓名' %>
            <%= f.text_field :name, class: "block w-full shadow-sm py-3 px-4 placeholder-gray-500 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md"%>
            <% if f.object.errors[:name] %>
	            <span class='text-red-600'><%= f.object.errors[:name].first %></span>
	          <% end %>
          </div>
          <div>
            <%= f.label :email, '信箱'%>
            <%= f.email_field :email, class:"block w-full shadow-sm py-3 px-4 placeholder-gray-500 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md" %>
              <% if f.object.errors[:email] %>
		            <span class='text-red-600'><%= f.object.errors[:email].first %></span>
	            <% end %>
          </div>
          <div>
            <%= f.label :address, '地址' %>
            <%= f.text_field :address, class:"block w-full shadow-sm py-3 px-4 placeholder-gray-500 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md" %>
              <% if f.object.errors[:address] %>
		            <span class='text-red-600'><%= f.object.errors[:address].first %></span>
            	<% end %>
          </div>
          <div>
           <%= f.label :cellphone, '行動電話' %>
           <%= f.text_field :cellphone, class:"block w-full shadow-sm py-3 px-4 placeholder-gray-500 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md" %>
             <% if f.object.errors[:cellphone] %>
			         <span class='text-red-600'><%= f.object.errors[:cellphone].first %></span>
		         <% end %>
       
          </div>
          <div>
            <%= f.label :telephone, '電話' %>
            <%= telephone_field(:reserve, :telephone,class:"block w-full shadow-sm py-3 px-4 placeholder-gray-500 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md") %>
          </div>

          <div>
            <%= f.label :brand, '洗衣機廠牌' %>
            <%= f.text_field :brand, placeholder: '例如:國際、三洋',class:"block w-full shadow-sm py-3 px-4 placeholder-gray-500 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md" %>
          </div>

          <div>
            <%= f.label :genre, '直立式/滾筒式', class: 'block' %>
            <%= f.select :genre,["直立式", "滾筒式"], class:'bg-white' %>
          </div>

          <div>
            <%= f.label :appointment, '希望時間' %>
            <%= f.datetime_field :appointment, class:"block w-full shadow-sm py-3 px-4 placeholder-gray-500 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md" %>
              <% if f.object.errors[:appointment] %>
                <span class='text-red-600'><%= f.object.errors[:appointment].first %></span>
              <% end %>
          </div>
          <div>
            <%= f.label :determine_time, '確定時間' %>
            <%= f.datetime_field :determine_time, min: Date.today, class:"block w-full shadow-sm py-3 px-4 placeholder-gray-500 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md"%>
          </div>

          <div>
            <%= f.label :remark, '備註' %>
            <%= f.text_area :remark,placeholder: '其他特殊需求',class:"block w-full shadow-sm py-3 px-4 placeholder-gray-500 focus:ring-indigo-500 focus:border-indigo-500 border border-gray-300 rounded-md" %>
          </div>

          <div>
            <%= f.label :status, '預約單狀態',class: 'block' %>
            <%= f.select :status, ['已取消','無法清洗','待確認', '預約成功','清洗完成'],class:"block w-full shadow-sm py-3 px-4 placeholder-gray-500 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md"  %>
          </div>

          <div>
            <%= f.submit '送出' ,class: "inline-flex justify-center py-3 px-6 border border-transparent shadow-sm text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mt-4"%>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/reserves/edit.html.erb
<%= render "form", reserve: @reserve %>

app/views/admin/reserves/index.html.erb
<h1 class= 'text-center'>所有預約單</h1>
<div class="text-center">
<%= form_with url:admin_search_path, method: :get do |f| %>
  <%= f.search_field :keyword %>
  <%= f.submit '搜尋' %>
<% end %>
</div>
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto ">
    <div class="py-6 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 ">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                姓名
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                地址
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Email
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                手機號碼
              </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                電話
              </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                廠牌
              </th>
               </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                直立/滾筒
              </th>
               </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                預期日期
              </th>
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                狀態
              </th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @reserves.each do |reserve| %>
            <tr class="bg-white">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                <%= reserve.name %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                <%= reserve.address %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                <%= reserve.email %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                 <%= reserve.cellphone %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                 <%= reserve.telephone %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                 <%= reserve.brand %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                <%= reserve.genre %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                <%= reserve.appointment.strftime("%Y/%m/%d %p%H:%M") %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                 <%= reserve.status %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                 <%= link_to '查看', admin_reserve_path(reserve) %>
                 <%= link_to '編輯', edit_admin_reserve_path(reserve) %>
                 <%= link_to '刪除', admin_reserve_path(reserve),     
                                                method: 'delete',
						                        data: { confirm: '確定嗎？', id: reserve.id } %>
              </td>
            </tr>          
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div class='text-center'>
  <%== pagy_nav(@pagy) %>
</div>

app/views/admin/reserves/show.html.erb
<h1 class="text-center">預約單</h1>
  <div class='text-center mt-4 text-blue-400 text-xl'>
    <%= link_to '本客戶歷史預約紀錄', reserves_path %>
    <%= link_to '編輯本預約單', edit_admin_reserve_path %>
  </div>
<div class="relative bg-white">
  <div class="absolute inset-0">
    <div class="absolute inset-y-0 left-0 w-1/2 "></div>
  </div>
  <div class="relative max-w-7xl mx-auto lg:grid lg:grid-cols-5">
    <div class="bg-white py-16 px-4 sm:px-6 lg:col-span-2 lg:px-8 lg:py-24 xl:pr-12">
      <div class="max-w-lg mx-auto">
        <h2 class="text-2xl font-extrabold tracking-tight text-blue-400 sm:text-3xl">
          衣級棒新北三重服務團隊
        </h2>
        <p class="mt-3 text-lg leading-6 text-black">
          衣級棒專業洗衣機清洗-清洗內槽-秉持著一顆服務熱忱的心。讓您不再為洗衣服而感到困擾， 給您一個舒適潔淨的洗衣空間。將每個家庭洗衣機的髒汙轉化成煥然一新的面貌。
        </p>
        <dl class="mt-8 text-base text-black">
          <div>
            <dt class="sr-only">Postal address</dt>
            <dd>
              <p>新北市三重區XX街XX巷XX號</p>
            </dd>
          </div>
          <div class="mt-6">
            <dt class="sr-only">Phone number</dt>
            <dd class="flex">
              <!-- Heroicon name: outline/phone -->
              <svg class="flex-shrink-0 h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
              </svg>
              <span class="ml-3">
                0933750166 劉師傅
              </span>
            </dd>
          </div>
          <div class="mt-3">
            <dt class="sr-only">Email</dt>
            <dd class="flex">
              <!-- Heroicon name: outline/mail -->
              <svg class="flex-shrink-0 h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              <span class="ml-3">
                washyou178@gmail.com
              </span>
            </dd>
          </div>
        </dl>
          <a href="https://www.facebook.com/LINE0933750166" class= 'block text-blue-400 text-2xl mt-10 '>衣級棒-新北三重粉絲專頁</a>

      </div>
    </div>
    <div class="bg-white py-16 px-4 sm:px-6 lg:col-span-3 lg:py-24 lg:px-8 xl:pl-12">
      <div class="max-w-lg mx-auto lg:max-w-none "> 
        <div>
          聯絡人: <%= @reserve.name %>
        </div>

        <div class='mt-2'>
          email: <%= @reserve.email %>
        </div>

        <div class='mt-2'>
          地址: <%= @reserve.address %>
        </div>

        <div class='mt-2'>
          行動電話: <%= @reserve.cellphone %>
        </div>

        <div class='mt-2'>
          電話: <%= @reserve.telephone %>
        </div>

        <div class='mt-2'>
          廠牌: <%= @reserve.brand %>
        </div>

        <div class='mt-2'>
          直立/滾筒: <%= @reserve.genre %>
        </div>

        <div class='mt-2'>
          希望時間: <%= @reserve.appointment %> 實際時間以師傅連絡後為主
        </div>

        <div class="mt-2">
          確定時間: <%= @reserve.determine_time %>
        </div>

        <div class='mt-2'>
          預約狀態: <%= @reserve.status %>
        </div>

        <div class='mt-2'>
          備註: <%= @reserve.remark %>
        </div>

        <div class='mt-8'>
          照片: <%= image_tag @reserve.image_url if @reserve.image_url.present? %>
        </div>
      </div>
    </div>
  </div>
</div>