config/routes.rb
Rails.application.routes.draw do

 

  devise_for :users , controllers:
                     { omniauth_callbacks: "users/omniauth_callbacks" }
                     { registrations: "users/registrations" }
  devise_scope :users do
  end
  namespace :admin, path: 'asigaiboho' do
    resources :reserves 
    resources :users
    get 'search', to: 'reserves#search'
    get 'searchs', to: 'users#searchs'
  end

    resources :reserves 
    root 'welcome#index'
    resources :users
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/welcome/index.html.erb
  <main class="lg:relative">
    <div class="mx-auto max-w-7xl w-full pt-16 pb-20 text-center lg:py-48 lg:text-left">
      <div class="px-4 lg:w-1/2 sm:px-8 xl:pr-16">
        <h1 class="text-4xl tracking-tight font-extrabold text-blue-400 sm:text-4xl md:text-4xl lg:text-4xl xl:text-5xl">
          <span class="block xl:inline">衣級棒-新北三重服務團隊</span>
        </h1>
        <p class="mt-3 max-w-md mx-auto text-lg text-gray-500 sm:text-xl md:mt-5 md:max-w-3xl">
          衣級棒專業洗衣機清洗-清洗內槽-秉持著一顆服務熱忱的心。讓您不再為洗衣服而感到困擾，給您一個舒適潔淨的洗衣空間。將每個家庭洗衣機的髒汙轉化成煥然一新的面貌。
        </p>
        <div class="mt-10 sm:flex sm:justify-center lg:justify-start">
          <div class="rounded-md shadow">
              <%= link_to '我要預約', new_reserve_path, class: "w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-4 md:text-lg md:px-10" %>
          </div>

          <div class="mt-3 rounded-md shadow sm:mt-0 sm:ml-3">
              <%= link_to '預約紀錄', reserves_path, class:"w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-indigo-600 bg-white hover:bg-gray-50 md:py-4 md:text-lg md:px-10"%>
          </div>
        </div>
      </div>
    </div>
    <div class="relative w-full h-64 sm:h-72 md:h-96 lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2 lg:h-full">
      <img class="absolute inset-0 w-full h-full object-cover" src="/uploads/衣級棒logo.jpg" alt="">
    </div>
  </main>
</div>