config/routes.rb
Rails.application.routes.draw do

 

  devise_for :users , controllers:
                     { omniauth_callbacks: "users/omniauth_callbacks" }
                     { registrations: "users/registrations" }
  devise_scope :users do
  end
  namespace :admin, path: 'asigaiboho' do
    resources :reserves 
    resources :users
    get 'search', to: 'reserves#search'
    get 'searchs', to: 'users#searchs'
  end

    resources :reserves 
    root 'welcome#index'
    resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>衣級棒新北三重預約系統</title>
    <meta name="google-site-verification" content="wJob4_XL-6FuUSFtRogZZApWp8TX9koBzjYU5_54V-w" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <div class= 'text-right mt-2 mr-2'>
      <% if current_user %>
      <%= link_to '首頁', root_path, class: "br-8" %>
      <%= link_to('登出', destroy_user_session_path, :method => :delete,class:"inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500") %>
      <%= link_to('修改密碼', edit_registration_path(:user),class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500") %>
    <% else %>
      <%= link_to '首頁', root_path %>
      <%= link_to('註冊', new_registration_path(:user), class:"inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500") %> 
      <%= link_to('登入', new_session_path(:user),class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500") %>
    <% end %>
  </div> 
  </head>

  <body>
    <%= render 'components/flash' %>
    <%= yield %>
  

  </body>
</html>